//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeePerformance
    {
        public int PerformanceID { get; set; }
        public int EmployeeID { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ReviewDate { get; set; }
        public decimal SalesVolume { get; set; }
        public decimal ProfitVolume { get; set; }
        public int CustomerSatisfactionScore { get; set; }
        public int ItemsSoldToday { get; set; }
        public int PeerReviewScore { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime CreatedAt { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
