//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RetailGuruEntities : DbContext
    {
        public RetailGuruEntities()
            : base("name=RetailGuruEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DesignationTable> DesignationTables { get; set; }
        public virtual DbSet<EmployeeAttendanceTable> EmployeeAttendanceTables { get; set; }
        public virtual DbSet<EmployeeEducationTable> EmployeeEducationTables { get; set; }
        public virtual DbSet<EmployeeTable> EmployeeTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
        public virtual DbSet<UserTypeTable> UserTypeTables { get; set; }
        public virtual DbSet<EmployeeSalaryTable> EmployeeSalaryTables { get; set; }
        public virtual DbSet<EmployeePerformance> EmployeePerformances { get; set; }
    }
}
